version: '3.4'

networks:
  default:
    driver: bridge

services:
  lacuna-rest-pki:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - default